FROM node:lts-alpine AS dependencies

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile


FROM node:lts-alpine AS development

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY . .

COPY --from=dependencies /usr/src/app/node_modules ./node_modules